CREATE TABLE VEM_SER.PAIS(
ID_PAIS NUMBER NOT NULL,
NOME VARCHAR2(50),
PRIMARY KEY (ID_PAIS)
);

CREATE SEQUENCE seq_pais
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE VEM_SER.ESTADO(
ID_ESTADO NUMBER NOT NULL,
ID_PAIS NUMBER NOT NULL,
NOME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_ESTADO),
CONSTRAINT FK_ID_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE SEQUENCE VEM_SER.SEQ_ESTADO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.CIDADE(
ID_CIDADE NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
NOME VARCHAR2(50),
PRIMARY KEY (ID_CIDADE),
CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE SEQUENCE VEM_SER.SEQ_CIDADE
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.BAIRRO(
ID_BAIRRO NUMBER NOT NULL,
ID_CIDADE NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PRIMARY KEY (ID_BAIRRO),
CONSTRAINT FK_ID_ESTADO_BAIRRO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
CONSTRAINT FK_ID_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

CREATE SEQUENCE VEM_SER.SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.ENDERECO(
ID_ENDERECO NUMBER NOT NULL,
ID_BAIRRO NUMBER NOT NULL,
ID_CIDADE NUMBER NOT NULL,
LOGRADOURO VARCHAR2(255) NOT NULL,
NUMERO NUMBER NOT NULL,
COMPLEMENTO VARCHAR2(100),
CEP VARCHAR2(9),
PRIMARY KEY(ID_ENDERECO),
CONSTRAINT FK_ID_CIDADE_ENDERECO FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE),
CONSTRAINT FK_ID_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO)
);



CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

SELECT * FROM PAIS
SELECT * FROM ESTADO
SELECT * FROM CIDADE
SELECT * FROM BAIRRO
SELECT * FROM ENDERECO

INSERT INTO PAIS (ID_PAIS, NOME) 
VALUES (SEQ_PAIS.NEXTVAL, 'BRASIL')

INSERT INTO PAIS (ID_PAIS, NOME) 
VALUES (SEQ_PAIS.NEXTVAL, 'AUSTRALIA')

INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) 
VALUES (SEQ_ESTADO.NEXTVAL, 1, 'BAHIA')

INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME)
VALUES (SEQ_ESTADO.NEXTVAL, 1, 'SÃO PAULO')
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME)
VALUES (SEQ_ESTADO.NEXTVAL, 2, 'VITORIA')

INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME)
VALUES (SEQ_ESTADO.NEXTVAL, 2, 'QUEENSLAND')

INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_CIDADE.NEXTVAL, 1, 'SALVADOR')

INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) 
VALUES (SEQ_CIDADE.NEXTVAL, 2, 'GUARULHOS')
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_CIDADE.NEXTVAL, 3, 'MELBOURN')

INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_CIDADE.NEXTVAL, 4, 'BRISBANE')

INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) 
VALUES (SEQ_BAIRRO.NEXTVAL, 1, 1, 'NAZARE')

INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) 
VALUES (SEQ_BAIRRO.NEXTVAL, 2, 2, 'VILA GALVÃO')

INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_BAIRRO.NEXTVAL, 3, 3, 'RICHMOND')

INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_BAIRRO.NEXTVAL, 4, 4, 'BRISBANE CITY')

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 1, 1, 'VILA ANSELMO', 17, 'LOJA', 40040230)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 1, 1, 'AVENIDA BRITO', 15, 'HOTEL', 40055000)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
VALUES (SEQ_ENDERECO.NEXTVAL, 2, 2, 'R GUARULHOS', 52, 'Mercado', 07022020)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 2, 2, 'RUA SANTA IZABEL', 12, 'CASA', 40040789)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
VALUES (SEQ_ENDERECO.NEXTVAL, 3, 3, 'CHURCH ST. RICHMOND', 437, 'RESTAURANTE', 3121)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 3, 3, 'BRIDGE RD', 571, 'CAFE', 3121)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 4, 4, 'ADELAIDE ST ', 232, 'ESCOLA', 5000)

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
VALUES (SEQ_ENDERECO.NEXTVAL, 4, 4, 'EAGLE ST.', 110, 'ESCOLA', 4000)
