SELECT * FROM PAIS ORDER BY NOME DESC 
SELECT LOGRADOURO, CEP FROM ENDERECO WHERE LOGRADOURO LIKE 'A%' OR LOGRADOURO LIKE 'a%'
SELECT * FROM ENDERECO WHERE CEP LIKE '%0'
SELECT * FROM ENDERECO WHERE NUMERO BETWEEN 1 AND 100
SELECT * FROM ENDERECO WHERE LOGRADOURO LIKE UPPER('RUA%') ORDER BY CEP DESC
SELECT COUNT(id_endereco) FROM ENDERECO
SELECT ID_CIDADE, COUNT(ID_ENDERECO) FROM ENDERECO GROUP BY ID_CIDADE

UPDATE endereco 
SET 
logradouro = 'rua das margaridas',
complemento = 'terreo'
WHERE ID_ENDERECO = 1 or ID_ENDERECO = 2
UPDATE endereco 
SET 
numero = 99999
WHERE ID_ENDERECO = 4
SELECT * FROM ENDERECO 

 WHERE numero = (SELECT MAX(numero) FROM ENDERECO)
 DELETE FROM ENDERECO  WHERE ID_ENDERECO = 4
 DELETE FROM ENDERECO 